version: '3'
services:
  redis:
    image: "${DOCKER_REGISTRY}/redis:6.0.5-alpine"
    container_name: distribution_redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT_DATA_DIR}/var/data/redis:/data
      - ${ROOT_DATA_DIR}/app/third-party/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    ports:
    - 6379:6379
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    restart: always